### ISSUE TITLE
Does not work on OS X

### ISSUE THREAD

**Issue by matthewhutchings** [Sparticuz/qpdf-aws-lambda#1]
AppImage is mainly for Ubuntu. Script does not work on OS X

**Comment by Sparticuz** [comment]
This script should work on any unix based system with access to `make`, `wget`, and `zip`. Do you have those dependencies installed? Are you receiving an error? The AppImage file is just a container that has the qpdf binary in it. This script extracts the binary, then creates a zip file so you can use it in AWS Lambda.

**Comment by mkabatek** [comment]
Can confirm doesn't work on macOS. Something to do with AppImage.

```
./qpdf.AppImage --appimage-extract
make: ./qpdf.AppImage: Permission denied
make: *** [build] Error 1
```

**Comment by mkabatek** [comment]
It would be nice to have an alternate method for generating the zip on macOS. I used a linux machine to generate the zip file. Once you have this zip file, in case anyone is wonder how to add this as a layer using cloudformation, and not have to do it manually.

Add the following to your Lambda function
```
Layers:
      - !Ref libs
```

Then add the following as a resource

```
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: qpdf-aws-lambda
      Description: Dependencies for qpdf.
      ContentUri: qpdf-aws-lambda/.
      CompatibleRuntimes:
        - nodejs12.x  
```

Have the unzipped file in your `sam` project in the directory `qpdf-aws-lambda`. Then you can use `sam deploy` and the layers will be created and you can use `node-qpdf` in your lambda function.
